"""
Django settings for pawfect project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-71)!zi6u3#r3a-u9adt-7fn^!5etal=rp*kwl0_z9g%a&#07*d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('VERCEL') is None

# Configured to accept localhost and any .vercel.app domain
ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost', '*']

# Vercel terminates HTTPS at its edge and forwards requests internally over HTTP,
# so Django needs to be told to trust the X-Forwarded-Proto header. Without this,
# request.is_secure() is always False and CSRF checks reject POST forms
# (login, signup, contact, booking, reviews) with a 403 on the live deployment.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # Ensures WhiteNoise handles static files in dev
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',

    # your apps
    'accounts',
    'adminpanel',
    'client',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serves static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pawfect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # project-level templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pawfect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Vercel's serverless functions run on a read-only filesystem, so a bundled
# db.sqlite3 file can't be written to (and, since it's in .gitignore, never
# even reaches the deployment). Use a real hosted database in production via
# a DATABASE_URL env var (e.g. from a Vercel Postgres / Neon / Supabase
# integration added in the Vercel dashboard's Storage tab), and fall back to
# the local SQLite file for local development. This matches Vercel's
# documented pattern for Django: https://vercel.com/docs/frameworks/full-stack/django
import urllib.parse

if os.environ.get('DATABASE_URL'):
    url = urllib.parse.urlparse(os.environ['DATABASE_URL'])
    query = urllib.parse.parse_qs(url.query)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path.lstrip('/'),
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port,
            'OPTIONS': {'sslmode': query.get('sslmode', ['require'])[0]},
        }
    }
else:
    # Local development only.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# No STATICFILES_DIRS needed: 'client' and 'adminpanel' are both in
# INSTALLED_APPS, so Django's AppDirectoriesFinder already picks up their
# static/ subfolders. Adding client/static here too just duplicated that
# source and caused harmless "skipped due to conflict" noise from collectstatic.

STATIC_ROOT = BASE_DIR / 'staticfiles_collected'

# Enables WhiteNoise to locate files directly from app directories during serverless runtime
WHITENOISE_USE_FINDERS = True

# Vercel automatically runs collectstatic (since STATIC_ROOT is set above) and
# serves the result from its CDN. This backend is one of Vercel's officially
# supported storages for that: https://vercel.com/docs/frameworks/full-stack/django#serving-static-assets
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
